using Microsoft.VisualStudio.TestTools.UnitTesting;
using adventofcode2019_day10.Day10Part2;
using Shouldly;

namespace adventofcode2019_day10Tests.Day10Part2.Part1
{
    [TestClass()]
    public class CalculateAngleTests
    {
        [TestMethod()]
        public void CalculateAngleTests_01()
        {
            // 3..........
            // 2.A........
            // 1..........
            // 0B.........
            //  0123456789
            Angle.CalculateInDegrees(2, 2, 0, 0).ShouldBe(225M);
        }
        [TestMethod()]
        public void CalculateAngleTests_02()
        {
            // 5..........
            // 4....A.....
            // 3..........
            // 2..........
            // 1..........
            // 0B.........
            //  0123456789
            Angle.CalculateInDegrees(4, 4, 0, 0).ShouldBe(225M);
        }
        [TestMethod()]
        public void CalculateAngleTests_03()
        {
            // 3..........
            // 2.B........
            // 1..........
            // 0A.........
            //  0123456789
            Angle.CalculateInDegrees(0, 0, 2, 2).ShouldBe(45M);
        }
    }
}